name: Trabajo Practico 1

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout del c贸digo fuente
      uses: actions/checkout@v2

    - name: Configurar Node.js
      uses: actions/setup-node@v2
      with:
        node-version: 18.16.0  # Mi versi贸n de Node.js con la que se ha creado el proyecto

    - name: Instalar dependencias
      run: npm install  # Instalar dependencias

   - name: Build for Android
      run: npx eas build -p android

    - name: Build for iOS
      run: npx eas build -p ios

    - name: Archive artifacts
      uses: actions/upload-artifact@v2
      with:
        name: build
        path: .expo
        
    - name: Ejecutar la aplicaci贸n
      run: npm start  # Compilar la aplicaci贸n

    - name: Ejecutar pruebas unitarias
      run: npm run test  # Ejecutar pruebas unitarias al componente react native
